# Глобальні параметри
global:
  token: USDT
  currency: PLN
  total_balance: 2431.00  # theoretical: bank + exchange

# Конфігурація Bybit API
bybit:
  api_key: ${BYBIT_API_KEY}
  api_secret: ${BYBIT_API_SECRET}
  testnet: false

# Telegram Bot конфіг
telegram:
  token: ${TELEGRAM_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}

# Конкретні оголошення, ідентифіковані за тегом у remark
ads:
  # SELL оголошення
  - tag: "#S1"
    type: SELL
    balance: max              # або 1120.50 — фіксована кількість
    min_limit: 100
    max_limit: 3600
    payment_methods: [159, 154, 139]

  - tag: "#S2"
    type: SELL
    balance: 850
    min_limit: 50
    max_limit: 2500
    payment_methods: [9, 14, 147]

  # BUY оголошення
  - tag: "#B1"
    type: BUY
    balance: max              # тут balance = total_balance - sum(SELL quantities)
    min_limit: 100
    max_limit: 1200
    payment_methods: [147]

  - tag: "#B2"
    type: BUY
    balance: 700
    min_limit: 200
    max_limit: 1800
    payment_methods: [159, 355]

# Стратегії визначення ціни
pricing:

  SELL:
    fixed_price: null               # якщо null — використати підбір
    fallback_price: 4.30
    min_price: 3.76                 # мінімальна допустима ціна (запобіжник)

    check_payment_methods: true
    allowed_payment_types: [159, 154, 139, 133, 14, 292, 147, 9, 22, 355]

    check_min_balance: true
    min_amount_threshold: 1000

    check_limit: true
    min_limit_threshold: 100
    max_limit_threshold: 3699

    check_register_days: true
    min_register_days: 185

    check_min_orders: true
    min_order_count: 50

    check_target_nicknames: true
    target_nicknames: ['Rezak', 'FastchangeUA']

  BUY:
    fixed_price: null
    fallback_price: 3.50
    max_price: 3.71                # максимальна допустима ціна (запобіжник)

    check_payment_methods: true
    allowed_payment_types: [159]

    check_min_balance: true
    min_amount_threshold: 1000.0

    check_limit: true
    min_limit_threshold: 100
    max_limit_threshold: 3600

    check_register_days: false
    min_register_days: 15

    check_min_orders: false
    min_order_count: 0

    check_target_nicknames: true
    target_nicknames: ['KryptoLady', 'Matvey 1975']
